name: Java CI with Gradle

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --warning-mode=all

      - name: Run tests with Gradle
        run: ./gradlew test --warning-mode=all
